basePath: /api/v1
definitions:
  models.Skill:
    properties:
      category:
        type: string
      exchange:
        type: string
      id:
        type: integer
      skill:
        type: string
      username:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      password:
        description: omitempty чтобы не светить в API
        type: string
      socialLink:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Trade Your Exp.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Авторизирует пользователя по введенным данным.
      parameters:
      - description: Пользователь авторизирован
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Пользователь успешно вошел
        "400":
          description: Неверный формат данных
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Авторизация пользовтеля
      tags:
      - users
  /register:
    post:
      consumes:
      - application/json
      description: Создание пользователя с заполнение требуемых полей.
      parameters:
      - description: Пользователь корректен
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Пользователь успешно создан
        "400":
          description: Неверный формат данных
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Создание пользователя
      tags:
      - users
  /skills:
    get:
      consumes:
      - application/json
      description: Вывод полного списка навыков.
      produces:
      - application/json
      responses:
        "200":
          description: Вывод пользовательских скиллов
        "400":
          description: Неверный формат
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Вывести все скиллы
      tags:
      - skills
    post:
      consumes:
      - application/json
      description: Создание нового запроса с описанием
      parameters:
      - description: Данные запроса навыка
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Skill'
      produces:
      - application/json
      responses:
        "201":
          description: Запрос навыка успешно создан
        "400":
          description: Неверный формат запроса
          schema:
            additionalProperties: true
            type: object
        "409":
          description: Конфликт при создании запроса
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Добавление запроса с дополнительным описанием
      tags:
      - skills
  /skills/{category}:
    get:
      consumes:
      - application/json
      description: Вывод полного списка скиллов по категории.
      parameters:
      - description: Категория скилла
        in: path
        name: category
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Вывод пользовательских скиллов
        "400":
          description: Неверный формат
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Категория не найдена
          schema:
            additionalProperties: true
            type: object
      summary: Вывести все скиллы по категории.
      tags:
      - skills
  /skills/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет запрос навыка по его ID
      parameters:
      - description: ID запроса
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Запрос навыка успешно удален
        "404":
          description: Неверный формат ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Запрос не найден
          schema:
            additionalProperties: true
            type: object
      summary: Удалить запрос
      tags:
      - skills
  /skills/desc:
    get:
      consumes:
      - application/json
      description: Вывод полного дополнительных описаний
      produces:
      - application/json
      responses:
        "200":
          description: Вывод списка доп. описаний
        "400":
          description: Неверный формат
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Вывести все доп.описания
      tags:
      - skills
  /skills/desc/{id}:
    get:
      consumes:
      - application/json
      description: Выводит описание по персональному skill_id
      parameters:
      - description: Вывод описания по skill_id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Вывод пользователя
        "400":
          description: Неверный формат Skill ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Вывод описания по skill_id
      tags:
      - skills
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет пользователя из базы данных по его UUID.
      parameters:
      - description: UUID пользователя
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Пользователь успешно удален
        "404":
          description: Неверный формат ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Удалить пользователя
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Обновляет данные в базе данных по его UUID.
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: string
      - description: Новые данные
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Пользователь успешно обновлен
        "400":
          description: Неверный формат ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Пользователь не найден
          schema:
            additionalProperties: true
            type: object
      summary: Обновить данные
      tags:
      - users
schemes:
- http
- https
swagger: "2.0"
